//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.34209
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using UnityEngine.UI;
using System.Collections;

public static class largeBGImageLoader {
	public static Sprite getImage(string srgsNoStr){

	string fFullPath = "";
	Sprite retSprite = null;
	Sprite[] charaBase;

	switch (srgsNoStr) {
	case "00":
		fFullPath = "advBackGroungImage/廊下背景02";
		charaBase = Resources.LoadAll<Sprite>(fFullPath);
		retSprite = charaBase[0];

		break;
			
	case "01":
		//運動場02
		fFullPath = "advBackGroungImage/運動場02";
		charaBase = Resources.LoadAll<Sprite>(fFullPath);
		retSprite = charaBase[0];
		
		break;


		}

	return retSprite;
	}
}

